spring:
    datasource:
        url: jdbc:mysql://localhost:3306/smart?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8
        username: root
        password: 12345678
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
        maxWait: 60000
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
      host: 127.0.0.1
      port: 6379
      password:

